spring.application.name=testing


# PostgreSQL database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/tododb
spring.datasource.username=postgres
spring.datasource.password=221276
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA configurations
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true


